version: "3.3"
services:

  node1:
    build:
      context: ./files
      dockerfile: ./Node-1/Dockerfile
    ports:
      - 8545:8545
      - 8645:8645
      - 30303:30303
    networks:
      paulinmaBlockchain:
        ipv4_address: 172.30.1.1

  node2:
    build:
      context: ./files
      dockerfile: ./Node-2/Dockerfile
    ports:
      - 8546:8556
      - 8646:8646
      - 30304:30304
    networks:
      paulinmaBlockchain:
        ipv4_address: 172.30.1.2

  node3:
    build:
      context: ./files
      dockerfile: ./Node-3/Dockerfile
    ports:
      - 8547:8557
      - 8647:8657
      - 30305:30305
    networks:
      paulinmaBlockchain:
        ipv4_address: 172.30.1.3

  node4:
    build:
      context: ./files
      dockerfile: ./Node-4/Dockerfile
    ports:
      - 8548:8558
      - 8648:8658
      - 30306:30306
    networks:
      paulinmaBlockchain:
        ipv4_address: 172.30.1.4

networks:
  paulinmaBlockchain:
    external: true
